services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-chat-app
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: chatapp
      DB_USERNAME: root
      DB_PASSWORD: Bipinsingh1
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: chatapp
      MYSQL_ROOT_PASSWORD: Bipinsingh1
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db_data:
